Repository Sylius/MolliePlugin, pull requests merged in 2025-04, with the labels that each got.

#107 [Maintenance][Admin] Fix product details template
  tests/Application/templates/bundles/SyliusAdminBundle/Product/Tab/_details.html.twig
Labels: Admin, Bug

#113 Minor improvements to 1.0 installtion guide
  README.md
  doc/legacy_installation.md
Labels: Enhancement

#112 Update installation guide for 2.0
  README.md
  UPGRADE-2.0.md
  config/services/resolver.xml
  config/state_machine/checkout.yaml
  doc/legacy_installation.md
  src/Entity/GatewayConfigTrait.php
  src/Entity/ProductTrait.php
  tests/Application/config/packages/_sylius.yaml
  tests/Application/config/packages/twig.yaml
Labels: Enhancement

#116 Update assets section in installtion guide to mention node 18 support.
  README.md
  doc/legacy_installation.md
Labels: Enhancement

#118 Add missing information about regenerated migrations in UPGRADE file
  UPGRADE-2.0.md
Labels: Maintenance, Enhancement

#119 Rename entry files to entrypoints
  UPGRADE-2.0.md
  assets/admin/entrypoint.js
  assets/shop/entrypoint.js
  doc/legacy_installation.md
  tests/Application/assets/admin/entry.js
  tests/Application/assets/admin/entrypoint.js
  tests/Application/assets/shop/entry.js
  tests/Application/assets/shop/entrypoint.js
  tests/Application/webpack.config.js
Labels: Enhancement

#120 Correct copied bundles paths, add information about importance of mollie script inclusion order
  README.md
  doc/legacy_installation.md
Labels: Enhancement

#122 [Maintenance] Minor fixes after renamings
  templates/Admin/Logger/_level.html.twig
  templates/Admin/MollieSubscription/Show/_breadcrumb.html.twig
Labels: Maintenance

#124 [Maintenance] Fix validation of recurring variants
  src/Form/Extension/ProductVariantRecurringExtension.php
  src/Form/Type/MollieIntervalType.php
  templates/ProductVariant/Tab/_recurring.html.twig
Labels: Admin

#121 [Maintenance] Define column names for all fields in DB mapping
  .github/workflows/build.yml
  config/doctrine/MollieMethodImage.orm.xml
  config/doctrine/MollieSubscription.orm.xml
  config/doctrine/MollieSubscriptionConfiguration.orm.xml
  config/doctrine/MollieSubscriptionSchedule.orm.xml
  tests/Application/config/packages/doctrine.yaml
Labels: Maintenance, Bug

#125 [Maintenance] Fix payment methods images handling
  UPGRADE-2.0.md
  config/services/resolver.xml
  src/Resolver/MolliePaymentMethodImageResolver.php
  templates/Admin/PaymentMethod/_mollieMethodsForm.html.twig
  templates/Shop/PaymentMollie/_form.html.twig
  tests/Application/config/packages/twig.yaml
Labels: Admin, Maintenance, Shop

#126 Fix payment methods translation
  src/Form/Type/PaymentTypeChoiceType.php
Labels: Admin

#127 [Maintenance] Fix invalid graph const in twig
  templates/Admin/MollieSubscription/Show/_sidebarTransitions.html.twig
Labels: Admin, Maintenance

#133 Resolve the issue with null GatewayConfig
  src/Validator/Constraints/PaymentMethodMollieChannelUniqueValidator.php
Labels: Bug

#135 Unify routing config name
  config/routes.yaml
  doc/legacy_installation.md
  tests/Application/config/routes.yaml
Labels: Maintenance

#136 Unify templates with OS
  tests/Application/templates/bundles/SyliusShopBundle/Checkout/SelectPayment/_payment.html.twig
  tests/Application/templates/bundles/SyliusShopBundle/Checkout/_support.html.twig
  tests/Application/templates/bundles/SyliusShopBundle/Common/Order/_payments.html.twig
  tests/Application/templates/bundles/SyliusShopBundle/Common/Order/_table.html.twig
  tests/Application/templates/bundles/SyliusShopBundle/Product/_info.html.twig
Labels: Enhancement

#140 rename routes config to the correct names
  config/routes.yaml
  config/routes/admin.yaml
  config/routes/admin/methods.yaml
  config/routes/admin/mollie_email_template.yaml
  config/routes/admin/mollie_logger.yaml
  config/routes/admin/mollie_logo.yaml
  config/routes/admin/mollie_subscription.yaml
  config/routes/admin/onboarding_wizard/completed.yaml
  config/routes/admin/onboarding_wizard/status.yaml
  config/routes/admin/partial_ship.yaml
  config/routes/admin/payment_link.yaml
  config/routes/admin/payment_refund.yaml
  config/routes/admin/product_type.yaml
  config/routes/shop.yaml
  config/routes/shop/applePay.yaml
  config/routes/shop/creditCardTranslation.yaml
  config/routes/shop/pageRedirect.yaml
  config/routes/shop/paymentFee.yaml
  config/routes/shop/paymentWebhook.yaml
  config/routes/shop/payum.yaml
  config/routes/shop/qrCode.yaml
  config/routes/shop/subscription_mollie.yaml
Labels: Maintenance, Enhancement

#144 Fix state machine configuration
  src/Resources/config/state_machine/payment_mollie_subscription.yaml
Labels: Bug

#142 Remove `Credit Cart` Maximum Amount Limit from Payment Method Configuration
  .gitignore
  src/Validator/Constraints/MollieGatewayConfigValidator.php
  tests/PHPUnit/Unit/Validator/MollieGatewayConfigValidatorTest.php
Labels: Enhancement

#147 Fix title in layout
  tests/Application/templates/bundles/SyliusAdminBundle/Layout/layout.html.twig
Labels: Bug

#152 Add upmerge for 2.1 branch
  .github/workflows/upmerge_pr.yaml
Labels: CI, DX

#148 Add Symfony Workflow support
  .github/workflows/build.yml
  config/config.yaml
  config/services/workflow.xml
  config/workflow/mollie_subscription.yaml
  config/workflow/mollie_subscription_manual.yaml
  config/workflow/payment_mollie_subscription.yaml
  config/workflow/sylius_shipment.yaml
  src/Entity/MollieSubscriptionInterface.php
  src/EventListener/Workflow/MollieSubscription/AbortSubscriptionGuardListener.php
  src/EventListener/Workflow/MollieSubscription/AfterActivateListener.php
  src/EventListener/Workflow/MollieSubscription/CompleteSubscriptionGuardListener.php
  src/EventListener/Workflow/MollieSubscription/SubscriptionScheduleSuccessListener.php
  src/EventListener/Workflow/SyliusOrderCheckout/ApplyPaymentSurchargeListener.php
  src/EventListener/Workflow/SyliusPayment/SubscriptionPaymentFailListener.php
  src/EventListener/Workflow/SyliusPayment/SubscriptionPaymentSuccessListener.php
  src/EventListener/Workflow/SyliusShipment/PurifyReadyShipmentsListener.php
  src/EventListener/Workflow/SyliusShipment/ResolveShipmentStateListener.php
  src/StateMachine/MollieRecurringTransitions.php
  src/StateMachine/MollieSubscriptionTransitions.php
  src/StateMachine/ShipmentTransitions.php
  src/Subscription/Guard/SubscriptionGuardInterface.php
  tests/Application/config/packages/sylius_state_machine_abstraction.yaml
Labels: Feature
